<a href="https://colab.research.google.com/github/correlative/collab-prtc/blob/main/numpy_access_modify_save.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
rand_arr = np.random.randint(1, 10, [6, 6])
rand_arr

array([[7, 8, 5, 8, 2, 8],
       [7, 8, 5, 9, 3, 2],
       [4, 5, 4, 6, 7, 8],
       [5, 5, 3, 3, 7, 9],
       [3, 2, 5, 3, 3, 1],
       [2, 5, 6, 7, 6, 4]])

In [3]:
print(f"a row: {rand_arr[3]}")

a row: [5 5 3 3 7 9]


In [4]:
print(f"uptill a row :\n{rand_arr[:2]}")

uptill a row :
[[7 8 5 8 2 8]
 [7 8 5 9 3 2]]


In [5]:
print(f"subset: \n{rand_arr[1:3]}")

subset: 
[[7 8 5 9 3 2]
 [4 5 4 6 7 8]]


In [6]:
neg_mat = np.random.randint(-5, 5, 6)
neg_mat

array([ 4, -2,  0,  3, -4,  3])

In [7]:
neg_mat

array([ 4, -2,  0,  3, -4,  3])

In [8]:
rand_arr[:] < 1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [9]:
print(f"less than zero: {rand_arr[rand_arr<0]}")

less than zero: []


In [10]:
print(f"more than zero: {rand_arr[rand_arr > 0]}")

more than zero: [7 8 5 8 2 8 7 8 5 9 3 2 4 5 4 6 7 8 5 5 3 3 7 9 3 2 5 3 3 1 2 5 6 7 6 4]


In [11]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [12]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matrix[0:1, 0:3]

array([[1, 2, 3]])

In [24]:
print(f"rand_arr : \n{rand_arr}")
print("------")
print(f"rand_arr[0:1, 0:3] : \n{rand_arr[0:1, 0:3]}")

rand_arr : 
[[7 8 5 8 2 8]
 [7 8 5 9 3 2]
 [4 5 4 6 7 8]
 [5 5 3 3 7 9]
 [3 2 5 3 3 1]
 [2 5 6 7 6 4]]
------
rand_arr[0:1, 0:3] : 
[[7 8 5]]


In [25]:
rand_arr[0:1, 0:3] = 11
print(f"rand_arr[0:1, 0:3] : \n{rand_arr[0:1, 0:3]}")

rand_arr[0:1, 0:3] : 
[[11 11 11]]


In [26]:
print(f"rand_arr : \n{rand_arr}")

rand_arr : 
[[11 11 11  8  2  8]
 [ 7  8  5  9  3  2]
 [ 4  5  4  6  7  8]
 [ 5  5  3  3  7  9]
 [ 3  2  5  3  3  1]
 [ 2  5  6  7  6  4]]


In [33]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [35]:
sub_mat = rand_arr[1:4, 2:5]
sub_mat

array([[5, 9, 3],
       [4, 6, 7],
       [3, 3, 7]])