<a href="https://colab.research.google.com/github/correlative/collab-prtc/blob/main/numpy_trig_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr1 = np.arange(0, 10)
arr2 = arr1.reshape((2, 5))
print(f"reshaped: {arr2}")

reshaped: [[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
print(f"sine: {np.sin(4)}")
print(f"cos: {np.cos(4)}")
print(f"tan: {np.tan(4)}")

sine: -0.7568024953079282
cos: -0.6536436208636119
tan: 1.1578212823495775


In [4]:
np.exp(2)

7.38905609893065

In [5]:
arr3 = np.array([2, 4, 6])
np.exp(arr3)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [6]:
np.log(2)

0.6931471805599453

In [7]:
np.log(arr3)

array([0.69314718, 1.38629436, 1.79175947])

In [8]:
np.log10(arr3)

array([0.30103   , 0.60205999, 0.77815125])

In [9]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

In [10]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [11]:
l3 = np.arange(1, 6)
l3

array([1, 2, 3, 4, 5])

In [12]:
l4 = np.arange(3, 8)
l4

array([3, 4, 5, 6, 7])

In [13]:
print(f"add : {l3 + l4}")
print(f"subs : {l3 - l4}")
print(f"mult : {l3 * l4}")
print(f"div : {l3 / l4}")
print(f"inverse : {1 / l3}")

add : [ 4  6  8 10 12]
subs : [-2 -2 -2 -2 -2]
mult : [ 3  8 15 24 35]
div : [0.33333333 0.5        0.6        0.66666667 0.71428571]
inverse : [1.         0.5        0.33333333 0.25       0.2       ]


In [14]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
mat1 = np.arange(1, 10).reshape(3, 3)
mat2 = np.eye(3)

In [20]:
mat3 = np.arange(11, 20).reshape(3, 3)
mat3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
np.transpose(mat3)

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [21]:
mat3.T

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [22]:
print(f"min: {np.min(mat3)}")
print(f"min: {np.max(mat3)}")

min: 11
min: 19
