<a href="https://colab.research.google.com/github/correlative/collab-prtc/blob/main/numpy_prtc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr_str = ["Mercedes", "BMW", "Porsche", "Audi", "Ferrari"]

In [3]:
arr_num = [1,2,3,4,5,6,7,8,9]

In [4]:
np_arr_str = np.array(arr_str)
np_arr_num = np.array(arr_num)

In [6]:
print(np_arr_str)
print(np_arr_num)

print("--------")

print(arr_str)
print(arr_num)

['Mercedes' 'BMW' 'Porsche' 'Audi' 'Ferrari']
[1 2 3 4 5 6 7 8 9]
--------
['Mercedes', 'BMW', 'Porsche', 'Audi', 'Ferrari']
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
print(type(arr_str))
print(type(np_arr_str))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
np_matrix = np.array([[1,2,3], [12,23,34], [123,234,456]])
print(type(np_matrix))
print(np_matrix)

<class 'numpy.ndarray'>
[[  1   2   3]
 [ 12  23  34]
 [123 234 456]]
