<a href="https://colab.research.google.com/github/correlative/collab-prtc/blob/main/numpy_random_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
rand_mat = np.random.rand(5)
rand_mat



array([0.98600699, 0.23516431, 0.97637364, 0.16873098, 0.0215549 ])

In [5]:
rand_mat_sq = np.random.rand(5, 5)
rand_mat_sq

array([[0.06936718, 0.06077761, 0.74465232, 0.09606513, 0.38071235],
       [0.80216127, 0.79486153, 0.93610271, 0.63164925, 0.64049447],
       [0.19765561, 0.20255833, 0.47796586, 0.16917768, 0.52621959],
       [0.38740044, 0.74052169, 0.69868122, 0.48319027, 0.88861285],
       [0.34004426, 0.79242323, 0.07699065, 0.90902279, 0.8350628 ]])

In [8]:
rand_mat_n = np.random.randn(5)
rand_mat_n


array([-0.22757873,  0.83157867,  0.36091241, -0.99253633,  1.0444742 ])

In [9]:
rand_mat_nsq = np.random.randn(5, 5)
rand_mat_nsq

array([[-0.91082895, -0.76784416, -0.1665933 , -0.18359341, -0.32418846],
       [ 0.4064156 ,  0.95818888,  0.85081074,  0.88234358, -1.35312086],
       [-0.20759954,  0.49625749, -1.40474622, -1.89796665, -1.4563397 ],
       [ 0.55622428, -0.28513933,  0.9121128 , -0.5548148 , -0.26254512],
       [ 0.68312743, -0.0172577 ,  2.24679061,  0.90630182,  0.80902524]])

In [10]:
print(f"mean of matrix: {np.mean(rand_mat_n)}")
print(f"mean of matrix: {np.mean(rand_mat_nsq)}")

mean of matrix: 0.20337004195884117
mean of matrix: -0.0033991900164435764


In [11]:
print(f"std of matrix: {np.std(rand_mat_n)}")
print(f"std of matrix: {np.std(rand_mat_nsq)}")

std of matrix: 0.7406525204591318
std of matrix: 0.9503328785711527


In [12]:
rand_mat_1 = np.random.randint(0, 5, 10)
print(f"random int: {rand_mat_1}")

random int: [0 0 2 3 0 4 1 0 3 0]


In [15]:
rand_mat_2 = np.random.randint(0, 5, [5, 5])
print(f"random int: \n{rand_mat_2}")

random int: 
[[0 3 2 2 0]
 [2 1 0 1 2]
 [1 2 2 4 2]
 [1 0 1 0 4]
 [2 0 4 4 1]]
